# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e9e4fb033620877bbf08eb419971eb98"
name = "byte-digital-dev"
application_url = "https://purposes-electoral-tutorial-cakes.trycloudflare.com"
embedded = true
handle = "byte-digital-dev"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = ["https://purposes-electoral-tutorial-cakes.trycloudflare.com/auth/callback", "https://purposes-electoral-tutorial-cakes.trycloudflare.com/auth/shopify/callback", "https://purposes-electoral-tutorial-cakes.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
